### ISSUE TITLE
Stuck at downloading chrome since 15 minutes

### ISSUE THREAD

**Issue by jessicastorm1986** [vasani-arpit/WBOT#9]
Here is the screenshot of the running exe

![wbot](https://user-images.githubusercontent.com/4909974/57174446-b1c47680-6e5c-11e9-8c90-8c8356f1738b.jpg)

Please help, i am on windows 8

**Comment by vasani-arpit** [comment]
Thanks for raising the issue.
This has been resolved in v0.5-beta. Please try it out.

**Comment by samik9** [comment]
![gzeapps — wbot-macos — wbot-macos — 97×26 2019-06-12 18-27-18](https://user-images.githubusercontent.com/50071744/59393166-11f1e680-8d40-11e9-8794-cc32158a0c4e.jpg)

The issue still with v0.7-beta MAC

**Comment by vasani-arpit** [comment]
Sorry. I was looking for a dynamic solution to the version problem but it seems like I am not understanding chrome versioning properly. also I don't have mac to test the project in. I am going to add hard coded version for mac to resolve this issue.

**Comment by vasani-arpit** [comment]
@samik9 
Issue resolved in #40 version 0.8 
Please check. It should work now.

**Comment by MAZETAM** [comment]
@vasani-arpit 

To get preferred chromium revision:

`return Number(JSON.parse(JSON.stringify(puppeteer))._launcher._preferredRevision);`

**Comment by vasani-arpit** [comment]
Thanks !! will check it out.
